### ISSUE TITLE
更新版本以后突然报错了

### ISSUE THREAD

**Issue by SakakiP** [NateScarlet/auto-derby#159] opened 2021-08-22 12:33 UTC
ERROR [20:32:47]:__main__:124: unexpected exception
Traceback (most recent call last):
  
    raise ValueError("plugin.register: duplicated name is not allowed: %s" % name)
ValueError: plugin.register: duplicated name is not allowed: limited_sale_close
这样的情况

**Comment by NateScarlet** [comment] 2021-08-22 12:45
Duplicate of #148

**Closed by NateScarlet** 2021-08-22 12:45 UTC
