### ISSUE TITLE
Recognize new shop ui

### ISSUE THREAD

**Issue by gentle-knight-13** [NateScarlet/auto-derby#291] opened 2022-04-12 05:41 UTC
The following implementation will likely need to be changed to recognize the new shop ui.
https://github.com/NateScarlet/auto-derby/blob/8060c172411afc3bf283a093733869f6a48ba0f3/auto_derby/scenes/single_mode/shop.py#L141-L171

logs:
```
INFO  [2022-04-12 14:01:56]:auto_derby.template:183: match: tmpl=tmpl<single_mode_shop_item_price.png>, pos=(131, 549), similarity=0.97
INFO  [2022-04-12 14:01:56]:auto_derby.template:183: match: tmpl=tmpl<single_mode_shop_item_price.png>, pos=(131, 657), similarity=0.97
INFO  [2022-04-12 14:01:56]:auto_derby.template:183: match: tmpl=tmpl<single_mode_shop_item_price.png>, pos=(131, 441), similarity=0.97
INFO  [2022-04-12 14:01:57]:auto_derby.jobs.nurturing:56: shop items
INFO  [2022-04-12 14:01:57]:auto_derby.jobs.nurturing:72: score:	40.00/19.45:	Item<蹄鉄ハンマー・極#52@36>	<in cart>
INFO  [2022-04-12 14:01:57]:auto_derby.jobs.nurturing:72: score:	32.65/19.45:	Item<にんじんBBQセット#25@36>	<in cart>
INFO  [2022-04-12 14:01:57]:auto_derby.jobs.nurturing:72: score:	37.06/26.47:	Item<スパルタメガホン#44@49>	<in cart>
INFO  [2022-04-12 14:01:57]:auto_derby.jobs.nurturing:72: score:	17.16/7.02:	Item<スピード戦術書#6@13>	<in cart>
INFO  [2022-04-12 14:01:57]:auto_derby.jobs.nurturing:72: score:	0.00/4.86:	Item<スピードのメモ帳#1@9>	
INFO  [2022-04-12 14:01:57]:auto_derby.jobs.nurturing:72: score:	0.00/14.59:	Item<プレーンカップケーキ#22@27>	
INFO  [2022-04-12 14:01:57]:auto_derby.jobs.nurturing:72: score:	0.00/24.31:	Item<根性アンクルウェイト#49@45>	
INFO  [2022-04-12 14:01:57]:auto_derby.jobs.nurturing:72: score:	8.00/72.94:	Item<効率練習のススメ#28@135>	<coin not enough>
INFO  [2022-04-12 14:01:57]:auto_derby.template:183: match: tmpl=tmpl<single_mode_shop_item_price.png>, pos=(131, 549), similarity=0.97
INFO  [2022-04-12 14:01:57]:auto_derby.template:183: match: tmpl=tmpl<single_mode_shop_item_price.png>, pos=(131, 657), similarity=0.97
INFO  [2022-04-12 14:01:57]:auto_derby.template:183: match: tmpl=tmpl<single_mode_shop_item_price.png>, pos=(131, 441), similarity=0.97
INFO  [2022-04-12 14:01:57]:auto_derby.scenes.single_mode.shop:150: exchange: Item<スパルタメガホン#44@49>
INFO  [2022-04-12 14:01:58]:auto_derby.template:199: no match: tmpl=('single_mode_shop_use_confirm_button.png', 'close_button.png')
INFO  [2022-04-12 14:01:58]:auto_derby.template:199: no match: tmpl=('single_mode_shop_use_confirm_button.png', 'close_button.png')
INFO  [2022-04-12 14:01:58]:auto_derby.template:199: no match: tmpl=('single_mode_shop_use_confirm_button.png', 'close_button.png')
```

new shop images:
Since it is displayed in a reduced size, you can check the original size by clicking.
<img src="https://user-images.githubusercontent.com/98640031/162888223-d85d4ca0-d1f4-4143-9976-f903ccfd12ff.png" width="25%"> <img src="https://user-images.githubusercontent.com/98640031/162888238-a1fad6a9-60fe-4bbf-8adf-239f6eadf80f.png" width="25%"> <img src="https://user-images.githubusercontent.com/98640031/162888243-a65f743e-9a13-46f8-826d-87295c19d979.png" width="25%">
<img src="https://user-images.githubusercontent.com/98640031/162888247-75f5eb98-6086-493f-a517-8c5e19a8d6e1.png" width="25%"> <img src="https://user-images.githubusercontent.com/98640031/162888252-6e2dd12c-71e2-48ef-be35-ddb68ca0fe37.png" width="25%">

others:
Now that you can select multiple items and purchase them at the same time, you may be able to optimize the item selection scene.

**Comment by gentle-knight-13** [comment] 2022-04-12 12:17
Relatedly, the UI for possession goods has also been updated.
images:
Since it is displayed in a reduced size, you can check the original size by clicking.
<img src="https://user-images.githubusercontent.com/98640031/162960255-0418db70-76c1-4da3-a460-116dd6a11361.png" width="25%"> <img src="https://user-images.githubusercontent.com/98640031/162960269-75776282-adb9-4f22-94cf-4fad2ce3f3f5.png" width="25%"> <img src="https://user-images.githubusercontent.com/98640031/162960279-22a65acc-7a54-4d29-a5ee-773d2ded59f2.png" width="25%">

**Comment by gentle-knight-13** [comment] 2022-04-16 11:40
It may be necessary to recognize when items are not available.

images:
Since it is displayed in a reduced size, you can check the original size by clicking.
<img src="https://user-images.githubusercontent.com/98640031/163673505-2a231eff-61f5-4fcb-98b8-a48df489df4a.png" width="25%">

**Comment by gentle-knight-13** [comment] 2022-04-16 15:52
For now, I have it working with the new shop UI. We have not optimized the purchase scene.
Also, it has not been rigorously tested and may behave unexpectedly.
https://github.com/gentle-knight-13/auto-derby/compare/8060c17...8313910

**Comment by Small-Ku** [comment] 2022-04-16 21:19
I changed some parts of the code to use the multiple-choice system in-game, but items are used after purchase by revisiting the item menu.
Small-Ku/auto-derby@8313910...2be5d86

**Comment by Small-Ku** [comment] 2022-04-17 08:36
Items are used right after purchases now. 
I test it in one nurturing only. More tests might be needed.
https://github.com/Small-Ku/auto-derby/commit/377440af49aa135ac976e5195247afb5e4e692e4

**Comment by gentle-knight-13** [comment] 2022-04-17 17:47
@Small-Ku 
good job. 👍 

> Items are used right after purchases now.
> I tested it once only. More tests might be needed.
> https://github.com/Small-Ku/auto-derby/compare/41b0bed...4b752a8

When moving from the store menu to the item menu and using multiple items,
the item recognition range needs to be adjusted.

<img src="https://user-images.githubusercontent.com/98640031/162960255-0418db70-76c1-4da3-a460-116dd6a11361.png" width="25%"> <img src="https://user-images.githubusercontent.com/98640031/163725781-3fa01057-8a5b-4376-a240-02fd1aa4306b.png" width="25%"> <img src="https://user-images.githubusercontent.com/98640031/163726158-29cdfdae-336c-4b1a-bf1b-405cf35225e9.png" width="35%">

The item recognition range must be adjusted for the range indicated in the following description.
```
対象の育成グッズと交換しました
使用する育成グッズの個数を選択してください
```
This is where adjustments need to be made.
https://github.com/Small-Ku/auto-derby/blob/377440a/auto_derby/scenes/single_mode/item_menu.py#L72

**Comment by gentle-knight-13** [comment] 2022-04-17 18:31
> I think min_y should be +70.
If possible, the recognition range should be changed according to the scene.
min_y = rp.vector(130, 540) -> min_y = rp.vector(200, 540)

This hung, so I think I need to think about other ways to fix it.

**Comment by gentle-knight-13** [comment] 2022-04-18 05:04
> This hung, so I think I need to think about other ways to fix it.

It seems likely that the hang is caused by my environment. Probably the effect of incorrect OCR correction settings for the item.

**Comment by Small-Ku** [comment] 2022-04-18 06:43
I am using an unsupported resolution. That's why I may not face the same error as yours.
Since there should be no matches of current quantity templates in the description, did you make some changes to the code of the item menu?
I think the min_y here should be the minimum height for an item. Therefore, it may not help this issue.

**Comment by gentle-knight-13** [comment] 2022-04-18 08:34
```
Since there should be no matches of current quantity templates in the description of your screenshot
```

If you say so, it's true ...
The screenshots are not the ones when there was a real problem.
I have attached a processed version so that the recognition range is easy to understand.

```
did you make some changes to the code of the item menu?
```

I haven't changed the code in the item menu.
The only other thing I can think of is that you may have made a mistake in the merge...

It is working for now, so we will see how it goes for a while.

**Comment by Small-Ku** [comment] 2022-04-18 09:23
You are right. It should be the problem mentioned in https://github.com/NateScarlet/auto-derby/blob/master/auto_derby/scenes/single_mode/item_menu.py#L78.
Taking your screenshot as an example, the min_y (130) currently, which is from the original bba8874, makes the recognition range under the red line.
The 200 that you recommend is the green line. Since it is kind of below the template (the grey rectangle) in your screenshot. I changed it into 194 with https://github.com/Small-Ku/auto-derby/commit/697507943da901eb6af389461bb8951d424c1319, which is the blue line instead.

<img src="https://user-images.githubusercontent.com/16464896/163786457-1582e42e-7345-4d4f-826d-4642eb2bf6c1.png" alt="A screenshot" width="25%">

**Comment by gentle-knight-13** [comment] 2022-04-18 09:39
Thank you for the commentary! 👍
I am happy to be able to help you solve the problem.
I will take in the correction and move it for a while.

**Comment by gentle-knight-13** [comment] 2022-04-19 11:36
> I will take in the correction and move it for a while.

I have nurtured it about 10 times since then and have not experienced any problems.
One thing I did notice is that when you purchase multiple items for the same status up in the shop, only one of them will be used. This is not too much of a problem, since they are used in the item menu afterwards...

**Comment by Small-Ku** [comment] 2022-04-19 12:29
> One thing I did notice is that when you purchase multiple items for the same status up in the shop, only one of them will be used.

This is unexpected behaviour. Some information loss in https://github.com/Small-Ku/auto-derby/blob/697507943da901eb6af389461bb8951d424c1319/auto_derby/scenes/single_mode/shop.py may cause it. I will look into it tomorrow.

**Comment by Small-Ku** [comment] 2022-04-21 14:30
It should be fixed with https://github.com/Small-Ku/auto-derby/commit/a3503a1ef8cc48541ecc137eb5d2e6b8b37e79af.
However, it may result in some OCR errors when trying to use some items multiple times, but the item is single use only in each turn.
![Item menu with a notification about an item cannot be used multiple times](https://user-images.githubusercontent.com/16464896/164480202-9777b927-267c-4f43-9d48-3ce07df444e4.png)
The notification in the centre of the screen may cover the item quantity or get into the item quantity area.

**Comment by gentle-knight-13** [comment] 2022-04-22 21:21
> The notification in the centre of the screen may cover the item quantity or get into the item quantity area.

I think this problem can be avoided by recognizing whether the increment button is enabled after selecting the item.

It's an idea, but since the coordinates of the increment button are already known, I think it's better to take a screenshot, calculate the button's bounding box from the coordinates, and match whether the button is valid after cropping.

**Comment by Small-Ku** [comment] 2022-04-23 13:39
The click effect of the game may affect the button in the screenshot. Therefore, it may be acceptable to reuse the template of the current quantity to check whether it is disabled. It is similar to the case in https://github.com/NateScarlet/auto-derby/blob/master/auto_derby/scenes/single_mode/item_menu.py#L159. So, I added a warning here while refactoring in https://github.com/Small-Ku/auto-derby/commit/d1d6588f205c2acc937807bc7fb63413cfe8c9ee.
Also, the issue may be solved by improving the item plan by considering the max item quantity that can be used in one turn too.

**Comment by NateScarlet** [comment] 2022-04-23 13:42
> Also, the issue may be solved by improving the item plan by considering the max item quantity that can be used in one turn too.

item plan already considered that, unless you changed item score in wrong way from plugin

**Comment by Small-Ku** [comment] 2022-04-23 14:51
> item plan already considered that, unless you changed item score in wrong way from plugin

Then, would the item quantity of return results from the plan be not limited to the max item quantity that can be used in one turn?
```
auto_derby.jobs.nurturing:136: score:	68.09	Training<gut=27 spd=13 pow=13 ski=11 vit=-28.0% fail=0% lv=5 ptn=gut@5,wis@5,spd@5!,wis@5!>;19.78 by Item<根性アンクルウェイト#49x2>;
auto_derby.jobs.nurturing:136: score:	53.93	SummerRest;
auto_derby.jobs.nurturing:136: score:	31.98	Training<sta=27 gut=9 ski=3 vit=-25.0% fail=0% lv=5 ptn=sta@5,spd@5!>;
auto_derby.jobs.nurturing:136: score:	25.60	Training<spd=13 pow=6 ski=2 vit=-27.0% fail=0% lv=5>;8.36 by Item<スピードアンクルウェイト#46x1>;
auto_derby.jobs.nurturing:136: score:	20.71	Training<pow=11 sta=7 ski=2 vit=-26.0% fail=0% lv=5>;
auto_derby.jobs.nurturing:136: score:	15.83	Training<wis=12 spd=4 ski=3 vit=5.0% fail=0% lv=5>;
auto_derby.jobs.nurturing:136: score:	-14.28	Race<札幌 turf 1800m G3 クイーンステークス>;2.60 by Item<蹄鉄ハンマー・匠#51x1>;
auto_derby.jobs.nurturing:136: score:	-14.34	Race<中京 turf 1600m G3 中京記念>;2.60 by Item<蹄鉄ハンマー・匠#51x1>;
auto_derby.jobs.nurturing:136: score:	-14.34	Race<新潟 turf 1000m G3 アイビスサマーダッシュ>;2.60 by Item<蹄鉄ハンマー・匠#51x1>;
auto_derby.jobs.nurturing:136: score:	-24.92	Race<福島 turf 1200m OP 福島テレビオープン>;
```
It triggered this warning.
```
auto_derby.scenes.single_mode.item_menu:201: skip limited item: Item<根性アンクルウェイト#49x2>
```
There is my installed plugin below. Some plugins are in https://github.com/Small-Ku/auto-derby/tree/feature/plugins/plugins.
I believe these plugins do not change the score.
```
auto_derby.plugin:48: installed: limited_sale_buy_first_3
auto_derby.plugin:48: installed: bluestacks_port
auto_derby.plugin:48: installed: more_g1
race_campaign:125: no race campaign today
auto_derby.plugin:48: installed: race_campaign
debug_to_log:12: <StreamHandler <stderr> (INFO)> is set t
debug_to_log:15: <RotatingFileHandler D:\dev\auto-derby\a
auto_derby.plugin:48: installed: debug_to_log
auto_derby.plugin:48: installed: no_event_prompt
auto_derby.plugin:48: installed: auto_crane
auto_derby.plugin:48: installed: afk_ocr
```
Also, the whole log is here:
[auto_derby.1.log](https://github.com/NateScarlet/auto-derby/files/8547433/auto_derby.1.log)

**Comment by NateScarlet** [comment] 2022-04-23 15:38
`Item<根性アンクルウェイト#49x2>` not means use this item twice

**Comment by Small-Ku** [comment] 2022-04-23 15:43
> `Item<根性アンクルウェイト#49x2>` not means use this item twice

Then how should I pass the item sequence to use it multiple times?

**Comment by NateScarlet** [comment] 2022-04-23 15:44
```
DEBUG [2022-04-23 21:47:49]:auto_derby.single_mode.item.plan:97: score:	82.13(225 coin)	バイタル20,バイタル20,バイタル20,根性アンクルウェイト,ブートキャンプメガホン
DEBUG [2022-04-23 21:47:49]:auto_derby.single_mode.item.plan:80: start compute for: Training<wis=12 ski=3 spd=2 vit=5.0% fail=23% lv=3 ptn=oth@5>, effort=15
DEBUG [2022-04-23 21:47:49]:auto_derby.single_mode.item.plan:97: score:	3.48(35 coin)	バイタル20
DEBUG [2022-04-23 21:47:49]:auto_derby.single_mode.item.plan:97: score:	7.28(105 coin)	バイタル20,ブートキャンプメガホン
INFO  [2022-04-23 21:47:49]:auto_derby.jobs.nurturing:136: score:	63.60	Training<spd=48 pow=27 ski=12 vit=-25.0% fail=65% lv=4 ptn=spd@5,wis@5,spd@5!>;87.22 by Item<バイタル20#16x3>,Item<バイタル20#16x2>,Item<バイタル20#16x1>,Item<ブートキャンプメガホン#45x1>;
```

**Comment by Small-Ku** [comment] 2022-04-23 15:49
Thanks for your explaination.

**Comment by NateScarlet** [comment] 2022-04-23 16:03
maybe we should set item.quantity to 0 after item score computed, since it cause such confusion

**Comment by Small-Ku** [comment] 2022-04-23 16:16
In my opinion, putting a comment to explain it in the item class would be better understood.

**Comment by Small-Ku** [comment] 2022-04-25 09:10
I think the pull request is completed with enough tests. I marked it as ready for review. If you are available, please help me review it to see whether there are any improvements required before merging. Thank you.

**Closed** 2022-04-26 17:13 UTC
Labels: bug

**Comment by gentle-knight-13** [comment] 2022-04-27 03:44
@Small-ku, @NateScarlet
Thanks for fixing the issue ! :+1:
