### ISSUE TITLE
ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by waraiotoko2501h** [NateScarlet/auto-derby#9] opened 2021-05-31 13:15 UTC
I tried 18318127a95c86dc6e69e0cc06f117fb8c5d3378.
Select the training menu all the way through, choose wise, and then stop.
[This is a screenshot taken just after stopping.](https://imgur.com/a/JEUzmcF)

>C:\test\auto-derby>py -3.8 -m auto_derby nurturing
INFO  [2021-05-31 22:08:59]:auto_derby.window:58: width=466 height=828
INFO  [2021-05-31 22:08:59]:auto_derby.window:60: already in wanted size
INFO  [2021-05-31 22:08:59]:__main__:52: game window: 12456814
DEBUG [2021-05-31 22:09:00]:auto_derby.template:49: screenshot
DEBUG [2021-05-31 22:09:00]:auto_derby.template:63: load: connecting.pos.png
DEBUG [2021-05-31 22:09:00]:auto_derby.template:63: load: connecting.png
DEBUG [2021-05-31 22:09:00]:auto_derby.template:165: not match: tmpl=tmpl<connecting.png>, pos=(344, 57), similarity=0.193
DEBUG [2021-05-31 22:09:00]:auto_derby.template:63: load: retry_button.pos.png
DEBUG [2021-05-31 22:09:00]:auto_derby.template:78: can not load: retry_button.pos.png: [Errno 2] No such file or directory: 'C:\\test\\auto-derby\\auto_derby\\templates\\retry_button.pos.png'
DEBUG [2021-05-31 22:09:00]:auto_derby.template:63: load: retry_button.png
DEBUG [2021-05-31 22:09:00]:auto_derby.template:165: not match: tmpl=tmpl<retry_button.png>, pos=(130, 799), similarity=0.379
DEBUG [2021-05-31 22:09:00]:auto_derby.template:63: load: nurturing_command_training.pos.png
DEBUG [2021-05-31 22:09:00]:auto_derby.template:63: load: nurturing_command_training.png
DEBUG [2021-05-31 22:09:00]:auto_derby.template:117: lightness match: tmpl=tmpl<nurturing_command_training.png>, similarity=1.0
INFO  [2021-05-31 22:09:00]:auto_derby.template:168: match: tmpl=tmpl<nurturing_command_training.png>, pos=(172, 655), similarity=0.94
DEBUG [2021-05-31 22:09:00]:auto_derby.ocr:69: match label: hash=3800f800f801f001e0010f001f703ff83cfc007e803fe01ffc0ffe01fe003c00, value=ジ, similarity=0.969
DEBUG [2021-05-31 22:09:00]:auto_derby.ocr:69: match label: hash=f00ff01ff81ff81ff01f001e001e001e001e001f001f001f001fff7ffffffe7f, value=ュ, similarity=0.969
DEBUG [2021-05-31 22:09:00]:auto_derby.ocr:69: match label: hash=fc3ffc3ffc3ffc1ff80f000000000000000000000000fe1fff3fff7ffffffe7f, value=ニ, similarity=0.961
DEBUG [2021-05-31 22:09:00]:auto_derby.ocr:69: match label: hash=fffffffffeff00f000f0c0f8e07fe07fe03fe003f000f800f80078003c001c00, value=ア, similarity=0.906
DEBUG [2021-05-31 22:09:00]:auto_derby.ocr:69: match label: hash=001e0c3ffe3fbe3f1e271c273c473e47fe27fc3ffc3ffe3ffe7f9e7f1c260000, value=級, similarity=0.922
DEBUG [2021-05-31 22:09:00]:auto_derby.ocr:69: match label: hash=ffffffffff3fff3fc01fc01fe007e007e003e001f800f800fc00fc00f8003000, value=7, similarity=0.844
DEBUG [2021-05-31 22:09:00]:auto_derby.ocr:69: match label: hash=fc7ffcfffcff0cf00cf0fcff3cf81ce01cf03cf8feff0ff007e007f003f80070, value=月, similarity=0.977
DEBUG [2021-05-31 22:09:00]:auto_derby.ocr:69: match label: hash=00008400c619c21fc01ff81ffe7fff7fcf37cf3fff3fef3fc71fc71fc71fc21f, value=後, similarity=0.820
DEBUG [2021-05-31 22:09:00]:auto_derby.ocr:69: match label: hash=8031c439c439cc31cc03c003f807fe3fe007fe7fffffffffe007c003c0038001, value=半, similarity=0.930
DEBUG [2021-05-31 22:09:00]:auto_derby.ocr:222: ocr result: ジュニア級7月後半
DEBUG [2021-05-31 22:09:00]:auto_derby.ocr:69: match label: hash=e007fc3ffe7f3e7c0c7c007c007e803fe01ff007fc017e007e00ff3fff7fff7f, value=2, similarity=0.898
DEBUG [2021-05-31 22:09:00]:auto_derby.ocr:69: match label: hash=c003f81ffc3f3e7c1f7c1ff80ff80ff81ff81ff81f783f7c7e7ffc3ff81fc001, value=0, similarity=0.867
DEBUG [2021-05-31 22:09:00]:auto_derby.ocr:69: match label: hash=000c001f801fc01fe01ff81f781e3c1e3e1e3f3fffffffffffff003f001e001e, value=4, similarity=0.906
DEBUG [2021-05-31 22:09:00]:auto_derby.ocr:222: ocr result: 204
DEBUG [2021-05-31 22:09:00]:auto_derby.ocr:69: match label: hash=c007f81ffc3f3e7c0efc007c007e003fc01ff007f8017c007e00ff7fffffff7f, value=2, similarity=0.906
DEBUG [2021-05-31 22:09:00]:auto_derby.ocr:69: match label: hash=e003fc1ffe3f1c3e003e003ee01fe01fe03f007e00fc0efc3f7fff3ffc1ff007, value=3, similarity=0.883
DEBUG [2021-05-31 22:09:00]:auto_derby.ocr:69: match label: hash=003880ffe0fffefffffffcff80ff00ff00ff00ff00ff00ff00ff00ff00ff00fe, value=1, similarity=0.906
DEBUG [2021-05-31 22:09:00]:auto_derby.ocr:222: ocr result: 231
DEBUG [2021-05-31 22:09:00]:auto_derby.ocr:69: match label: hash=003880ffe0fffffffffffeff80ff00ff00ff00ff00ff00ff00ff00ff00ff007e, value=1, similarity=0.914
DEBUG [2021-05-31 22:09:00]:auto_derby.ocr:69: match label: hash=003c807ff0fffefffffffeff80ff00ff00ff00ff00ff00ff00ff00ff00ff003e, value=1, similarity=0.922
DEBUG [2021-05-31 22:09:00]:auto_derby.ocr:69: match label: hash=fc1ffe3ffe3f3e003e00fe07fe1ffe3f3c7e007800f8007c3e3efe3ff80fe003, value=5, similarity=0.805
DEBUG [2021-05-31 22:09:00]:auto_derby.ocr:222: ocr result: 115
DEBUG [2021-05-31 22:09:00]:auto_derby.ocr:69: match label: hash=000080fff0fffcfffefffcff80ff80ff00ff00ff00ff00ff00ff00ff00ff003e, value=1, similarity=0.883
DEBUG [2021-05-31 22:09:00]:auto_derby.ocr:69: match label: hash=e007fc3ffc7f1c7c007c003ee03fe03fe07f00fc00fc04fc3ffcfe7ffc3fe007, value=3, similarity=0.906
DEBUG [2021-05-31 22:09:00]:auto_derby.ocr:69: match label: hash=c007f03ff83f3c101e001e00ff1fff3f7f7e1ff81ef03ef87c7cfc7ff01f8007, value=6, similarity=0.852
DEBUG [2021-05-31 22:09:00]:auto_derby.ocr:222: ocr result: 136
DEBUG [2021-05-31 22:09:00]:auto_derby.ocr:69: match label: hash=001e803ff03ffe3ffe3ffc3fc03f807f80ff80ff807f803f803f803f807f003f, value=1, similarity=0.859
DEBUG [2021-05-31 22:09:00]:auto_derby.ocr:69: match label: hash=e007fc1ffc3f1c7e007c003fe03fe03fe07f007c00fc047c3f7eff7ffc1fe007, value=3, similarity=0.852
DEBUG [2021-05-31 22:09:00]:auto_derby.ocr:69: match label: hash=fe0fff7ffe7ffc7f803f801fc00fc007e007f003f003f001f801f801f801f800, value=7, similarity=0.852
DEBUG [2021-05-31 22:09:00]:auto_derby.ocr:222: ocr result: 137
INFO  [2021-05-31 22:09:00]:auto_derby.jobs.nurturing:561: update context: Context<turn=13,vit=0.654,spd=204,sta=231,pow=115,per=136,int=137>
DEBUG [2021-05-31 22:09:00]:auto_derby.template:63: load: nurturing_scheduled_race_opening_banner.pos.png
DEBUG [2021-05-31 22:09:00]:auto_derby.template:63: load: nurturing_scheduled_race_opening_banner.png
DEBUG [2021-05-31 22:09:00]:auto_derby.template:165: not match: tmpl=tmpl<nurturing_scheduled_race_opening_banner.png>, pos=(302, 681), similarity=0.169
INFO  [2021-05-31 22:09:00]:auto_derby.template:186: no match: tmpl=('nurturing_scheduled_race_opening_banner.png',)
DEBUG [2021-05-31 22:09:01]:auto_derby.template:49: screenshot
DEBUG [2021-05-31 22:09:01]:auto_derby.template:63: load: nurturing_training_confirm.pos.png
DEBUG [2021-05-31 22:09:01]:auto_derby.template:63: load: nurturing_training_confirm.png
DEBUG [2021-05-31 22:09:01]:auto_derby.template:117: lightness match: tmpl=tmpl<nurturing_training_confirm.png>, similarity=0.9607843137254902
INFO  [2021-05-31 22:09:01]:auto_derby.template:168: match: tmpl=tmpl<nurturing_training_confirm.png>, pos=(53, 727), similarity=0.98
DEBUG [2021-05-31 22:09:02]:auto_derby.template:49: screenshot
DEBUG [2021-05-31 22:09:03]:auto_derby.template:49: screenshot
DEBUG [2021-05-31 22:09:04]:auto_derby.template:49: screenshot
DEBUG [2021-05-31 22:09:05]:auto_derby.template:49: screenshot
DEBUG [2021-05-31 22:09:05]:auto_derby.template:49: screenshot
DEBUG [2021-05-31 22:09:05]:auto_derby.template:117: lightness match: tmpl=tmpl<nurturing_training_confirm.png>, similarity=0.9607843137254902
INFO  [2021-05-31 22:09:05]:auto_derby.template:168: match: tmpl=tmpl<nurturing_training_confirm.png>, pos=(53, 727), similarity=0.97
DEBUG [2021-05-31 22:09:05]:auto_derby.ocr:69: match label: hash=c001e003e003e003e003f003ff7fffffffffffffe003e003e003e003e003c001, value=+, similarity=0.906
DEBUG [2021-05-31 22:09:05]:auto_derby.ocr:69: match label: hash=000cc01fe01ffc1ffe1f801f001f001e003e00fe00ff80ffc0ffc0ffc0ff003f, value=1, similarity=0.805
DEBUG [2021-05-31 22:09:05]:auto_derby.ocr:222: ocr result: +1
DEBUG [2021-05-31 22:09:05]:auto_derby.ocr:155: ocr result is empty
DEBUG [2021-05-31 22:09:05]:auto_derby.ocr:69: match label: hash=c001e003e003e003e003e007ff7fffffffffffffe003e003e003e003e003c001, value=+, similarity=0.922
DEBUG [2021-05-31 22:09:06]:auto_derby.ocr:69: match label: hash=ffffffff007f003e001f800fc007e007e007f003f001f001f801f801f801f800, value=7, similarity=0.875
DEBUG [2021-05-31 22:09:06]:auto_derby.ocr:222: ocr result: +7
DEBUG [2021-05-31 22:09:06]:auto_derby.ocr:155: ocr result is empty
DEBUG [2021-05-31 22:09:06]:auto_derby.ocr:155: ocr result is empty
DEBUG [2021-05-31 22:09:06]:auto_derby.ocr:69: match label: hash=8003c007c007c007c007c00ffeffffffffffffffc007c007c007c007c0078003, value=+, similarity=0.828
DEBUG [2021-05-31 22:09:06]:auto_derby.ocr:222: ocr result: +
Traceback (most recent call last):
  File "C:\Users\UserName\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\UserName\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\test\auto-derby\auto_derby\__main__.py", line 80, in <module>
    main()
  File "C:\test\auto-derby\auto_derby\__main__.py", line 53, in main
    job()
  File "C:\test\auto-derby\auto_derby\jobs\nurturing.py", line 599, in nurturing
    _handle_training(ctx)
  File "C:\test\auto-derby\auto_derby\jobs\nurturing.py", line 148, in _handle_training
    t = Training.from_traning_scene(screenshot)
  File "C:\test\auto-derby\auto_derby\jobs\nurturing.py", line 496, in from_traning_scene
    self.skill = _ocr_traning_effect(img.crop((387, t, 450, b)))
  File "C:\test\auto-derby\auto_derby\jobs\nurturing.py", line 466, in _ocr_traning_effect
    return int(text.lstrip("+"))
ValueError: invalid literal for int() with base 10: ''

**Comment by NateScarlet** [comment] 2021-05-31 13:19
I need screenshot of speed training that contains +1 +7.

sometime restart can fix the problem, because character is dynamic.

**Comment by NateScarlet** [comment] 2021-05-31 13:22
Also you can post the image to github directly, i prefer that.

**Comment by waraiotoko2501h** [comment] 2021-05-31 13:27
ok
speed training
![2021-05-31_22h26_35](https://user-images.githubusercontent.com/751160/120200476-55acc600-c25f-11eb-84b3-1f9c8d338566.png)

**Comment by waraiotoko2501h** [comment] 2021-05-31 13:28
Apparently, the OCR is failing.

**Comment by NateScarlet** [comment] 2021-05-31 13:34
I can reproduce, working on it

**Comment by NateScarlet** [comment] 2021-05-31 13:47
![图片](https://user-images.githubusercontent.com/21083014/120202577-54789a80-c259-11eb-8246-efd9042849fd.png)
The cause of this problem is the text outline is not closed perfectly (1px black gap on left-buttom of `1`) 
I can fix this by add a erode filter or adjust threshold, investigating which one is better

**Comment by NateScarlet** [comment] 2021-05-31 14:01
Fixed by increase sharpen level

**Closed** 2021-05-31 14:01 UTC
