### ISSUE TITLE
864x1536 分辨率剧本识别错误

### ISSUE THREAD

**Issue by akhialomgir** [NateScarlet/auto-derby#178] opened 2021-09-05 06:13 UTC
青春杯与URA将左上角日历区域a to区块错误识别
![20210905135722](https://user-images.githubusercontent.com/50533365/132117193-b0d53b4d-9b78-4c1a-9ad8-eaede5f7c777.png)
![20210905141225](https://user-images.githubusercontent.com/50533365/132117421-248133c8-5217-4038-a492-543053713ee7.jpg)

**Comment by NateScarlet** [comment] 2021-09-05 06:17
只支持 9:16 的屏幕

Duplicate of #132

**Comment by NateScarlet** [comment] 2021-09-05 06:21
不对 你这的不是带刘海 是你截图不知为啥不全

**Comment by NateScarlet** [comment] 2021-09-05 06:23
需要 auto_derby.log 和 debug/last_screenshot.png

**Comment by akhialomgir** [comment] 2021-09-05 06:36
> 
> 
> 需要 auto_derby.log 和 debug/last_screenshot.png

DEBUG [14:34:36]:auto_derby.ocr:151: match label: value=川, current=200036003ec016c784c783073307370632041a0418061ce68eef8eef86ef820f, match=18c018e718e718e718e718e718e718e71ce71ce71ce71ce70ee70ee70fe706c2, similarity=0.281
WARNING[14:34:36]:auto_derby.ocr:116: using low similarity label: hash=200036003ec016c784c783073307370632041a0418061ce68eef8eef86ef820f, value=川, similarity=0.28125
DEBUG [14:34:36]:auto_derby.ocr:361: ocr result: )川
ERROR [14:34:36]:__main__:123: unexpected exception
Traceback (most recent call last):
  File "Z:\home\akhia\TMP\auto-derby\auto_derby\__main__.py", line 119, in <module>
    main()
  File "Z:\home\akhia\TMP\auto-derby\auto_derby\__main__.py", line 90, in main
    job()
  File "Z:\home\akhia\TMP\auto-derby\auto_derby\jobs\nurturing.py", line 221, in nurturing
    spec[_spec_key(tmpl)](ac)
  File "Z:\home\akhia\TMP\auto-derby\auto_derby\jobs\nurturing.py", line 88, in _ac_handle_turn
    _handle_turn(ac.ctx)
  File "Z:\home\akhia\TMP\auto-derby\auto_derby\jobs\nurturing.py", line 41, in _handle_turn
    scene.recognize(ctx)
  File "Z:\home\akhia\TMP\auto-derby\auto_derby\scenes\single_mode\command.py", line 82, in recognize
    ctx.update_by_command_scene(template.screenshot(max_age=0))
  File "Z:\home\akhia\TMP\auto-derby\auto_derby\single_mode\context.py", line 312, in update_by_command_scene
    self.date = _ocr_date(screenshot.crop(date_bbox))
  File "Z:\home\akhia\TMP\auto-derby\auto_derby\single_mode\context.py", line 57, in _ocr_date
    year_end = text.index("級") + 1
ValueError: substring not found

调整了之后出现了这个报错

**Comment by NateScarlet** [comment] 2021-09-05 07:13
需要 auto_derby.log 和 debug/last_screenshot.png

我无法复现就无法解决

**Comment by NateScarlet** [comment] 2021-09-05 07:49
adb 最低建议分辨率 1920x1080 我之前测的时候这个分辨率才能和 DMM 960x540 匹配

**Comment by akhialomgir** [comment] 2021-09-05 07:52
> 
> 
> 需要 auto_derby.log 和 debug/last_screenshot.png
> 
> 我无法复现就无法解决

[auto_derby.log](https://github.com/NateScarlet/auto-derby/files/7111165/auto_derby.log)

![last_screenshot](https://user-images.githubusercontent.com/50533365/132119595-0d9cb0bd-4bfe-4157-aadf-ce983179b65d.png)

**Closed** 2021-09-05 08:38 UTC
Labels: bug
